# 0x74617465.sh â€” red team site
url: "https://0x74617465.sh"
baseurl: ""

plugins:
  - jekyll-sitemap

collections:
  writeups:
    output: true
    permalink: /writeups/:path/

defaults:
  - scope:
      path: ""
      type: writeups
    values:
      layout: writeup
